# Вставьте этот блок внутрь server { ... } для site.moncraft.space в /etc/nginx/sites-available/
location /monl/ {
    alias /monl/;
    autoindex off;
    add_header Access-Control-Allow-Origin *;
    add_header Cache-Control "no-cache, must-revalidate";
}
